<a href="https://colab.research.google.com/github/uavinash15/Machine-Learning/blob/main/Simple_Linear_Regression%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Simple Linear Regression**

 Predicting MBA Salary from Grade in 10th Marks

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
mba_salary_df=pd.read_csv('MBA Salary.csv')
mba_salary_df

    S. No.  Percentage in Grade 10  Salary
0        1                   62.00  270000
1        2                   76.33  200000
2        3                   72.00  240000
3        4                   60.00  250000
4        5                   61.00  180000
5        6                   55.00  300000
6        7                   70.00  260000
7        8                   68.00  235000
8        9                   82.80  425000
9       10                   59.00  240000
10      11                   58.00  250000
11      12                   60.00  180000
12      13                   66.00  428000
13      14                   83.00  450000
14      15                   68.00  300000
15      16                   37.33  240000
16      17                   79.00  252000
17      18                   68.40  280000
18      19                   70.00  231000
19      20                   59.00  224000
20      21                   63.00  120000
21      22                   50.00  260000
22      23                   69.00  300000
23      24                   52.00  120000
24      25                   49.00  120000
25      26                   64.60  250000
26      27                   50.00  180000
27      28                   74.00  218000
28      29                   58.00  360000
29      30                   67.00  150000
30      31                   75.00  250000
31      32                   60.00  200000
32      33                   55.00  300000
33      34                   78.00  330000
34      35                   50.08  265000
35      36                   56.00  340000
36      37                   68.00  177600
37      38                   52.00  236000
38      39                   54.00  265000
39      40                   52.00  200000
40      41                   76.00  393000
41      42                   64.80  360000
42      43                   74.40  300000
43      44                   74.50  250000
44      45                   73.50  360000
45      46                   57.58  180000
46      47                   68.00  180000
47      48                   69.00  270000
48      49                   66.00  240000
49      50                   60.80  300000

In [ ]:
mba_salary_df.head(10)

   S. No.  Percentage in Grade 10  Salary
0       1                   62.00  270000
1       2                   76.33  200000
2       3                   72.00  240000
3       4                   60.00  250000
4       5                   61.00  180000
5       6                   55.00  300000
6       7                   70.00  260000
7       8                   68.00  235000
8       9                   82.80  425000
9      10                   59.00  240000

In [ ]:
mba_salary_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   S. No.                  50 non-null     int64
 1   Percentage in Grade 10  50 non-null     float64
 2   Salary                  50 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 1.3 KB

In [ ]:
import statsmodels.api as sm
X=sm.add_constant(mba_salary_df['Percentage in Grade 10']) # adds a new column with constand value
print(X)

    const  Percentage in Grade 10
0     1.0                   62.00
1     1.0                   76.33
2     1.0                   72.00
3     1.0                   60.00
4     1.0                   61.00
5     1.0                   55.00
6     1.0                   70.00
7     1.0                   68.00
8     1.0                   82.80
9     1.0                   59.00
10    1.0                   58.00
11    1.0                   60.00
12    1.0                   66.00
13    1.0                   83.00
14    1.0                   68.00
15    1.0                   37.33
16    1.0                   79.00
17    1.0                   68.40
18    1.0                   70.00
19    1.0                   59.00
20    1.0                   63.00
21    1.0                   50.00
22    1.0                   69.00
23    1.0                   52.00
24    1.0                   49.00
25    1.0                   64.60
26    1.0                   50.00
27    1.0                   74.00
28    1.0                   58.00
29    1.0                   67.00
30    1.0                   75.00
31    1.0                   60.00
32    1.0                   55.00
33    1.0                   78.00
34    1.0                   50.08
35    1.0                   56.00
36    1.0                   68.00
37    1.0                   52.00
38    1.0                   54.00
39    1.0                   52.00
40    1.0                   76.00
41    1.0                   64.80
42    1.0                   74.40
43    1.0                   74.50
44    1.0                   73.50
45    1.0                   57.58
46    1.0                   68.00
47    1.0                   69.00
48    1.0                   66.00
49    1.0                   60.80

In [ ]:
X.head(5)

   const  Percentage in Grade 10
0    1.0                   62.00
1    1.0                   76.33
2    1.0                   72.00
3    1.0                   60.00
4    1.0                   61.00

In [ ]:
Y=mba_salary_df['Salary']

Splitting the Dataset into Training and Validation Sets

In [ ]:
X

    const  Percentage in Grade 10
0     1.0                   62.00
1     1.0                   76.33
2     1.0                   72.00
3     1.0                   60.00
4     1.0                   61.00
5     1.0                   55.00
6     1.0                   70.00
7     1.0                   68.00
8     1.0                   82.80
9     1.0                   59.00
10    1.0                   58.00
11    1.0                   60.00
12    1.0                   66.00
13    1.0                   83.00
14    1.0                   68.00
15    1.0                   37.33
16    1.0                   79.00
17    1.0                   68.40
18    1.0                   70.00
19    1.0                   59.00
20    1.0                   63.00
21    1.0                   50.00
22    1.0                   69.00
23    1.0                   52.00
24    1.0                   49.00
25    1.0                   64.60
26    1.0                   50.00
27    1.0                   74.00
28    1.0                   58.00
29    1.0                   67.00
30    1.0                   75.00
31    1.0                   60.00
32    1.0                   55.00
33    1.0                   78.00
34    1.0                   50.08
35    1.0                   56.00
36    1.0                   68.00
37    1.0                   52.00
38    1.0                   54.00
39    1.0                   52.00
40    1.0                   76.00
41    1.0                   64.80
42    1.0                   74.40
43    1.0                   74.50
44    1.0                   73.50
45    1.0                   57.58
46    1.0                   68.00
47    1.0                   69.00
48    1.0                   66.00
49    1.0                   60.80

In [ ]:
Y

0     270000
1     200000
2     240000
3     250000
4     180000
5     300000
6     260000
7     235000
8     425000
9     240000
10    250000
11    180000
12    428000
13    450000
14    300000
15    240000
16    252000
17    280000
18    231000
19    224000
20    120000
21    260000
22    300000
23    120000
24    120000
25    250000
26    180000
27    218000
28    360000
29    150000
30    250000
31    200000
32    300000
33    330000
34    265000
35    340000
36    177600
37    236000
38    265000
39    200000
40    393000
41    360000
42    300000
43    250000
44    360000
45    180000
46    180000
47    270000
48    240000
49    300000
Name: Salary, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

# skleran=scikit learn

In [ ]:
train_X,test_X,train_Y,test_Y=train_test_split(X,
                                              Y,
                                              train_size=0.8,
                                              random_state=100)

In [ ]:
train_X

    const  Percentage in Grade 10
0     1.0                   62.00
11    1.0                   60.00
18    1.0                   70.00
45    1.0                   57.58
38    1.0                   54.00
25    1.0                   64.60
26    1.0                   50.00
35    1.0                   56.00
17    1.0                   68.40
7     1.0                   68.00
47    1.0                   69.00
31    1.0                   60.00
32    1.0                   55.00
19    1.0                   59.00
21    1.0                   50.00
13    1.0                   83.00
1     1.0                   76.33
4     1.0                   61.00
12    1.0                   66.00
27    1.0                   74.00
40    1.0                   76.00
22    1.0                   69.00
29    1.0                   67.00
9     1.0                   59.00
16    1.0                   79.00
44    1.0                   73.50
48    1.0                   66.00
46    1.0                   68.00
14    1.0                   68.00
41    1.0                   64.80
2     1.0                   72.00
34    1.0                   50.08
30    1.0                   75.00
10    1.0                   58.00
15    1.0                   37.33
23    1.0                   52.00
39    1.0                   52.00
3     1.0                   60.00
24    1.0                   49.00
8     1.0                   82.80

In [ ]:
train_X.count()

const                     40
Percentage in Grade 10    40
dtype: int64

In [ ]:
test_X

    const  Percentage in Grade 10
6     1.0                    70.0
36    1.0                    68.0
37    1.0                    52.0
28    1.0                    58.0
43    1.0                    74.5
49    1.0                    60.8
5     1.0                    55.0
33    1.0                    78.0
20    1.0                    63.0
42    1.0                    74.4

In [ ]:
test_X.count()

const                     10
Percentage in Grade 10    10
dtype: int64

In [ ]:
train_Y

0     270000
11    180000
18    231000
45    180000
38    265000
25    250000
26    180000
35    340000
17    280000
7     235000
47    270000
31    200000
32    300000
19    224000
21    260000
13    450000
1     200000
4     180000
12    428000
27    218000
40    393000
22    300000
29    150000
9     240000
16    252000
44    360000
48    240000
46    180000
14    300000
41    360000
2     240000
34    265000
30    250000
10    250000
15    240000
23    120000
39    200000
3     250000
24    120000
8     425000
Name: Salary, dtype: int64

In [ ]:
train_Y.count()

np.int64(40)

In [ ]:
test_Y

6     260000
36    177600
37    236000
28    360000
43    250000
49    300000
5     300000
33    330000
20    120000
42    300000
Name: Salary, dtype: int64

In [ ]:
test_Y.count()

np.int64(10)

In [ ]:
import statsmodels.api as sm

In [ ]:
mba_salary_lm=sm.OLS(train_Y,train_X).fit() # x is Independent values, # Y= dependent values

Printing Estimated Parameters and Interpreting Them

In [ ]:
print(mba_salary_lm.params)

const                     30587.285652
Percentage in Grade 10     3560.587383
dtype: float64

Regression Model summary using Python

In [ ]:
mba_salary_lm.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                          Results: Ordinary least squares
===================================================================================
Model:                    OLS                   Adj. R-squared:          0.190
Dependent Variable:       Salary                AIC:                     1008.8680
Date:                     2025-08-22 11:45      BIC:                     1012.2458
No. Observations:         40                    Log-Likelihood:          -502.43
Df Model:                 1                     F-statistic:             10.16
Df Residuals:             38                    Prob (F-statistic):      0.00287
R-squared:                0.211                 Scale:                   5.0121e+09
-----------------------------------------------------------------------------------
                         Coef.     Std.Err.    t    P>|t|     [0.025       0.975]
-----------------------------------------------------------------------------------
const                  30587.2857 71869.4497 0.4256 0.6728 -114904.8088 176079.3801
Percentage in Grade 10  3560.5874  1116.9258 3.1878 0.0029    1299.4892   5821.6855
-----------------------------------------------------------------------------------
Omnibus:                    2.048              Durbin-Watson:                 2.611
Prob(Omnibus):              0.359              Jarque-Bera (JB):              1.724
Skew:                       0.369              Prob(JB):                      0.422
Kurtosis:                   2.300              Condition No.:                 413
===================================================================================
Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly
specified.
"""